# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ile_kat', models.IntegerField()),
                ('ile_wiz', models.IntegerField()),
                ('ile_prec', models.IntegerField()),
                ('ile_spons', models.IntegerField()),
                ('ile_sidewide', models.IntegerField()),
                ('ile_satelit', models.IntegerField()),
                ('extra', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='agreement start date')),
                ('end_date', models.DateTimeField(verbose_name='agreement completion end 6 mts')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='task start date')),
                ('end_date', models.DateTimeField(verbose_name='task completion date')),
                ('status_change_date', models.DateTimeField(verbose_name='status_change')),
                ('prio', models.BooleanField(default=False)),
                ('for_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Status')),
            ],
        ),
    ]
