# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20171014_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='extra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(),
        ),
    ]
