# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20171015_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='task completion date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='status_change'),
        ),
    ]
