# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20171015_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('d', 'do zrobienia'), ('k', 'robione po stronie klienta'), ('n', 'w trakcie u nas'), ('z', 'zrobione')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='stat_change'),
        ),
    ]
