# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_auto_20171018_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('d', 'Do zrobienia'), ('k', 'W trakcie - u klienta'), ('g', 'W trakcie - Gebuko'), ('z', 'Zrobione')], default='d', max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
