# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_auto_20171020_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='completion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(verbose_name='start'),
        ),
    ]
