# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_auto_20171020_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prio',
            new_name='prior',
        ),
    ]
